Download chromium and set path to binary
gemini-testing/hermione-headless-chrome pull request #2
Opened 2019-09-02 07:52 UTC by TheNech

Плагин загружает указанную в конфиге версию Хромиума (или последнюю, если ничего не указано), устанавливает опцию `headless` и путь к бинарному файлу в конфиг указанного браузера перед запуском тестов.

2019-09-02 13:29 UTC, CatWithApple requested changes

2019-09-02 13:29 UTC, CatWithApple commented on lib/chrome.js
> +const {REVISIONS_PATH: revisionsPath} = require('./constants/defaults');
зачем REVISIONS_PATH перегонять в revisionsPath? 
в коде же будет проще понять, что REVISIONS_PATH - это константа

2019-09-02 13:29 UTC, CatWithApple commented on .gitignore
> +lib/constants/revisions.json
не стоит выкачивать внешние ресурсы в директорию с кодом проекта.
обычно для этого используют поддиректории в home или temp.

в крайнем случае можно выделить отдельную папку в корне проекта. но будут проблемы, если папка node_modules окажется read only  (это более чем возможно)

2019-09-02 13:29 UTC, CatWithApple commented on index.js
> +            const chromiumPath = await chrome.getChromiumPath();
почему getChromiumPath, если основное действие - это Downloading?

2019-09-02 13:29 UTC, CatWithApple commented on index.js
> +            chrome.setUp(chromiumPath);
зачем гонять chromiumPath между двумя методами одного объекта?

и почему бы не объединить getChromiumPath и setUp для вызова в hermione.on?

2019-09-02 13:29 UTC, CatWithApple commented on lib/chrome.js
> +    static create(config, browser) {
плохо понимаю смысл статического метода create, который ничего не делает.

2019-09-02 13:29 UTC, CatWithApple commented on lib/chrome.js
> +    async setUp(chromiumPath) {
функция не ассинхронная же

2019-09-02 13:29 UTC, CatWithApple commented on lib/chrome.js
> +        return;
зачем?

2019-09-02 13:29 UTC, CatWithApple commented on index.js
> +            chrome.setUp(chromiumPath);
а нужен ли вообще класс Chrome? ООП - не серебрянная пуля.

2019-09-02 13:29 UTC, CatWithApple commented on lib/chrome.js
> +        chromeOptions.args = (_.isArray(chromeOptions.args)) ? _.union(chromeOptions.args, ['headless']) : ['headless'];
isArray и union тут нужны?
можно было бы чуть попроще написать:
```
const args = chromeOptions.args || [];
chromeOptions.args = [...args, 'headless'];
```

2019-09-02 13:29 UTC, CatWithApple commented on lib/chrome.js
> +    async _getChromiumRevision(ver) {
ver лучше не сокращать, imho

2019-09-02 13:29 UTC, CatWithApple commented on lib/chrome.js
> +        const response = await got(baseUrl);
1. got может упасть из-за проблем с сетью, сервером и пр. 
2. try/catch с информативной ошибкой нет даже на самом верхнем уровне плагина. 
3. есть смысл добавить ретраев для сетевых запросов. например, через p-retry.

2019-09-02 13:29 UTC, CatWithApple commented on lib/chrome.js
> +        if (ver.length === 1) {
почему такое условие?

2019-09-02 13:29 UTC, CatWithApple commented on lib/chrome.js
> +        const versionObj = _.isEmpty(ver) ? versions[0] : _.find(versions, (o) => _.startsWith(o.version, ver));
почему название аргумента "o"?

2019-09-02 13:29 UTC, CatWithApple commented on lib/chrome.js
> +        const versionObj = _.isEmpty(ver) ? versions[0] : _.find(versions, (o) => _.startsWith(o.version, ver));
гарантируется ли упорядоченность массива versions  по полю version?

2019-09-02 13:29 UTC, CatWithApple commented on lib/chrome.js
> +            throw new Error('Unknown browser version');
в текст ошибки можно накидать деталей. и не только сюда

2019-09-02 13:29 UTC, CatWithApple commented on lib/chrome.js
> +        const versions = JSON.parse(response.body);
JSON.parse тоже может кинуть ошибку.

2019-09-02 13:29 UTC, CatWithApple commented on lib/config.js
> +        browserId: option({
parseEnv и parseCli есть по умолчанию?

2019-09-02 13:29 UTC, CatWithApple commented on lib/constants/defaults.js
> +        installPath: homedir(),
мне больше привычнее запись  `os.homedir()`

2019-09-02 13:29 UTC, CatWithApple commented on lib/utils.js
> +exports.getRevisionFromFile = async (ver, path) => {
кажется, будет логичнее поменять аргументы местами (path сделать первым). 
getRevisionFromFile(path, ver)
writeRevisionToFile(path, ver, revision)

2019-09-02 13:29 UTC, CatWithApple commented on lib/utils.js
> +    let exist = null;
используй pathExists
https://github.com/jprichardson/node-fs-extra/blob/HEAD/docs/pathExists.md

2019-09-02 13:29 UTC, CatWithApple commented on lib/utils.js
> +        await fs.writeFile(path, JSON.stringify({}));
зачем запись в функции чтения? не надо так

2019-09-02 13:29 UTC, CatWithApple commented on lib/utils.js
> +    revisionsFromFile[ver] = revision;
могут быть проблемы при параллельном запуске с разными параметрами. 
используя глобальный объект, ты рискуешь потереть данные.
а ещё есть риск параллельной записи в один файл. мы сейчас решаем это с помощью flock из fs-ext. но тут, думаю, нужно просто обернуть чтение и запись в try/catch с выводом ошибки, но без падения. не такие важные данные и храним.

2019-09-02 14:21 UTC, TheNech commented on .gitignore
> +lib/constants/revisions.json
Этот файл один из методов создает, изначально его нет. Есть папка node_modules может быть только на чтение, наверное, лучше home использовать.
Тогда при запуске плагина создавать поддиректорию в home? Ее и для бинарников браузера можно использовать

2019-09-02 14:22 UTC, CatWithApple commented on .gitignore
> +lib/constants/revisions.json
да

2019-09-02 14:23 UTC, TheNech commented on index.js
> +            const chromiumPath = await chrome.getChromiumPath();
Он возвращает путь к бинарнику и не скачивает повторно, если ранее скачал.

2019-09-02 14:25 UTC, TheNech commented on index.js
> +            chrome.setUp(chromiumPath);
> и почему бы не объединить getChromiumPath и setUp для вызова в hermione.on

Согласен. Были проблемы с синхронизацией, поэтому они вызываются отдельно. Объединю

2019-09-02 14:28 UTC, TheNech commented on lib/chrome.js
> +        if (ver.length === 1) {
Если запрашивать версию ниже 10, например, 7, то при выборе из массива будет выбрана 70., а не 7.

2019-09-02 14:31 UTC, TheNech commented on lib/chrome.js
> +        const versionObj = _.isEmpty(ver) ? versions[0] : _.find(versions, (o) => _.startsWith(o.version, ver));
> почему название аргумента "o"?

Сокращение от Object из примера документации по lodash

2019-09-02 14:32 UTC, TheNech commented on lib/chrome.js
> +        const versionObj = _.isEmpty(ver) ? versions[0] : _.find(versions, (o) => _.startsWith(o.version, ver));
versions - массив объектов, у которых есть поле `version` с полным названием версии (например, 76.0.130.0)

2019-09-02 14:34 UTC, CatWithApple commented on lib/chrome.js
> +        if (ver.length === 1) {
то же самое будет при "70" и "700". 
сравнение корректно лишь временно

2019-09-02 14:35 UTC, TheNech commented on lib/utils.js
> +    revisionsFromFile[ver] = revision;
Не хотелось еще раз считывать файл перед записью. Не учел параллельный запуск, исправлю

2019-09-02 14:39 UTC, CatWithApple commented on lib/chrome.js
> +        const versionObj = _.isEmpty(ver) ? versions[0] : _.find(versions, (o) => _.startsWith(o.version, ver));
> Сокращение от Object из примера документации по lodash

хотя бы obj пусть будет.

> versions - массив объектов, у которых есть поле version с полным названием версии (например, 76.0.130.0)

не ответил на вопрос про упорядоченность. например, сейчас там три версии 76 мажора. `_. find` вернет первое совпадение. если порядок не гарантируется гуглом, то в коде проблема.

2019-09-02 15:08 UTC, TheNech commented on lib/chrome.js
> +        const versionObj = _.isEmpty(ver) ? versions[0] : _.find(versions, (o) => _.startsWith(o.version, ver));
> не ответил на вопрос про упорядоченность

Номера версий упорядочены по убыванию

2019-09-02 15:51 UTC, CatWithApple commented on lib/chrome.js
> +        const versionObj = _.isEmpty(ver) ? versions[0] : _.find(versions, (o) => _.startsWith(o.version, ver));
приложи в комментариях ссылку на документ, который это гарантирует, или сделай сам гарантию в коде.
не нужно полагаться на наблюдение текущего состояния, завтра оно может измениться.

2019-09-04 07:28 UTC, TheNech commented on lib/config.js
> +        browserId: option({
Это необязательные поля. У меня опции строковые, поэтому можно не указывать

2019-09-06 11:02 UTC, TheNech commented
/fixed @DudaGod @CatWithApple

2019-09-06 11:39 UTC, CatWithApple commented
нужно удалить .DS_Store и добавить их в gitignore

2019-09-06 13:20 UTC, TheNech commented
/fixed @CatWithApple

2019-09-06 15:11 UTC, CatWithApple commented on README.md
> +* **version** (optional) `Boolean` - Chromium version; recomended format - `XX`; latest stable version by default.
recomended  -> recommended

2019-09-06 15:11 UTC, CatWithApple commented on README.md
> +* **version** (optional) `Boolean` - Chromium version; recomended format - `XX`; latest stable version by default.
recomended format - `XX`
Тут нужна не рекомендация, а описание возможностей.

2019-09-06 15:11 UTC, CatWithApple commented on README.md
> +* **chromiumBasePath** (optional) `String` - path to create directory for downloaded Chromium binary; *home directory* by default.
`chromiumBasePath` - не очевидно, что это локальная папка кеша. мб `cachePath` ?
`path to create directory for downloaded` - можно опустить часть про создание

2019-09-06 15:11 UTC, CatWithApple commented on lib/chrome.js
> +        config.installPath = await utils.makeChromiumDir(config.chromiumBasePath);
зачем installPath записывать именно в config, а не просто в this?
config не должен меняться (кроме исключительных случаев)

2019-09-06 15:11 UTC, CatWithApple commented on lib/chrome.js
> +    async _getChromiumPath() {
название функции не отображает главное действие

2019-09-06 15:11 UTC, CatWithApple commented on lib/chrome.js
> +                if (err.message === 'Response code 404 (Not Found)') {
в else может сделаем throw? сейчас мы теряем информацию об ошибке, которая может помочь пользователю самостоятельно исправить ситуацию

2019-09-06 15:11 UTC, CatWithApple commented on lib/chrome.js
> +        const revisionFromFile = await utils.getRevisionFromFile(osName, version);
getRevisionFromFile - обычно при такой формулировке требуется передать в параметрах путь до файла, из которого будем читать. 
думаю, есть смысл переименовать

2019-09-06 15:11 UTC, CatWithApple commented on lib/chrome.js
> +        for (let i = 0; i < CHROMIUM_RETRIES_COUNT; i++) {
оставить бы комментарий почему нам нужен такой перебор

2019-09-06 15:11 UTC, CatWithApple commented on lib/constants/defaults.js
> +    REVISIONS_PATH: path.join(process.cwd(), 'lib/constants/revisions.json'),
может поместм хромиумы и revisions.json в одну папку?

2019-09-06 15:11 UTC, CatWithApple commented on lib/constants/revisions.json
> +{"mac":{"60":"474896","61":"488512","62":"499098","63":"508578","64":"520840","65":"530368","66":"540271","67":"550418","68":"561733","69":"576753","70":"587811","71":"599028","72":"612398","73":"625
prettify it, please

2019-09-06 15:11 UTC, CatWithApple commented on lib/utils.js
> +    const chromiumDirPath = path.join(basePath, PLUGIN_NAME);
кажется, что PLUGIN_NAME должен входить в config.chromiumBasePath

2019-09-06 15:11 UTC, CatWithApple commented on lib/utils.js
> +    if (!exists) {
можно использовать ensureDir
https://github.com/jprichardson/node-fs-extra/blob/HEAD/docs/ensureDir.md

2019-09-06 15:11 UTC, CatWithApple commented on lib/utils.js
> +    const platform = process.platform;
можно так
const {platform, arch} = process;

2019-09-06 15:11 UTC, CatWithApple commented on lib/utils.js
> +    if (osName === 'win64') {
можно сделать две функции getOsName, добавив специфики в название. сейчас код выглядит хрупко из-за этого if

2019-09-06 15:11 UTC, CatWithApple commented on lib/utils.js
> +const getOsName = () => {
предлагаю переименовать getOsName -> getOSName

2019-09-06 15:11 UTC, CatWithApple commented on lib/utils.js
> +    const revision = REVISIONS_FROM_FILE[osName][version];
можно сразу вернуть значение без создания новой переменной

2019-09-06 15:11 UTC, CatWithApple commented on lib/utils.js
> +        version = await getLastStableMajor(osName);
желательно избегать переопределения параметров функции
https://eslint.org/docs/rules/no-param-reassign

2019-09-06 15:11 UTC, CatWithApple commented on lib/utils.js
> +        response = await got(url, {json: true, retry: 5});
магическую константу 5 можно вынести в файл с константами

2019-09-06 15:11 UTC, CatWithApple commented on lib/utils.js
> +    const revision = response.body.chromium_base_position;
тут тоже не обязательно создавать переменную, чтобы сразу же её вернуть

2019-09-06 15:11 UTC, CatWithApple commented on lib/utils.js
> +        throw new Error('Unsupported platform for downloading Chromium');
только одна причина для пустого body?
в других запросах нет явной проверки body в теле функции. точно ок?

2019-09-06 15:11 UTC, CatWithApple commented on lib/utils.js
> +    const compareVersions = (a, b) => {
наверняка есть пакет в npm, который это делает.

2019-09-06 15:11 UTC, CatWithApple commented on lib/utils.js
> +        throw new Error('Passed Chromium version was not found');
можно в текст ошибки добавить shortVer

2019-09-06 15:11 UTC, CatWithApple commented on lib/utils.js
> +        : _.find(versions, (item) => _.startsWith(item, shortVer));
тут будет проблема с   '72.1' и '72.11'
может есть пакет в npm? :)

2019-09-06 15:11 UTC, CatWithApple commented on package.json
> +    "revisions": "node scripts/updateRevisions"
в названии скрипта можно добавить действие. сейчас не понятно

2019-09-06 15:11 UTC, CatWithApple commented on package.json
> +    "chromium": "^2.1.1",
где используется?

2019-09-06 15:11 UTC, CatWithApple commented on scripts/updateRevisions.js
> +    const file = await fs.readFile(REVISIONS_PATH);
я понимаю, что вряд ли файла не будет или он будет битым, но неплохо это предусмотреть

2019-09-06 15:11 UTC, CatWithApple commented on scripts/updateRevisions.js
> +module.exports = updateRevisions();
зачем экспорт?
функция асинхронная, сделай корректную обработку ошибок

2019-09-06 15:11 UTC, CatWithApple commented on test/unit/lib/utils.js
> +    let REVISIONS_FROM_FILE = {'linux': {'76': '6525'}};
почему let?

2019-09-06 15:11 UTC, CatWithApple commented on scripts/updateRevisions.js
> +    for (let osName of supportedOs) {
let -> const

2019-09-08 13:00 UTC, TheNech commented on lib/constants/defaults.js
> +    REVISIONS_PATH: path.join(process.cwd(), 'lib/constants/revisions.json'),
revisions.json теперь приезжает вместе с пакетом, т.е. он этот файл не меняется в ходе работы, а хромиумы скачиваются по мере необходимости

2019-09-08 13:06 UTC, TheNech commented on lib/utils.js
> +        throw new Error('Unsupported platform for downloading Chromium');
Запрос возвращает пустой массив, если неверно указать платформу, отсюда такие проверка и сообщение

2019-09-08 13:07 UTC, TheNech commented on lib/utils.js
> +        : _.find(versions, (item) => _.startsWith(item, shortVer));
У них в версиях минор всегда нулю равен, но я поищу пакет

2019-09-08 13:25 UTC, TheNech commented on lib/utils.js
> +    const chromiumDirPath = path.join(basePath, PLUGIN_NAME);
То есть если не указать путь для хромиумов в конфиге, то пусть просто в home скачивает?

2019-09-08 13:41 UTC, TheNech commented on test/unit/lib/utils.js
> +    let REVISIONS_FROM_FILE = {'linux': {'76': '6525'}};
Здесь другой стаб был раньше

2019-09-08 17:39 UTC, TheNech commented on lib/utils.js
> +    if (osName === 'win64') {
Этот if - следствие особенностей API. Если добавить еще один метод получения ОС, возникнут неудобства в других методах и некоторая путаница. Может пусть так остается?

2019-09-08 17:40 UTC, TheNech commented on lib/utils.js
> +    const compareVersions = (a, b) => {
Действительно, есть. Добавил

2019-09-08 17:42 UTC, TheNech commented on lib/utils.js
> +        : _.find(versions, (item) => _.startsWith(item, shortVer));
Какова функциональность пакета должна быть? Поведение то ожидаемое, да и способ версионирования Хромиума, кажется, позволяет обойтись `startsWith` и точкой в версии, если ее нет

2019-09-09 08:17 UTC, TheNech commented
/fixed @DudaGod @CatWithApple

2019-09-09 13:11 UTC, DudaGod requested changes
тесты пока не смотрел

2019-09-09 13:11 UTC, DudaGod commented on README.md
> +NB: plugin searches builds starting from last stable version, but downloaded developers version. Builds for some versions may not be found.
он всегда устанавливает dev версию? Я бы тут ссылок добавил на сайты chromium-а где сказано про декремент версий. И что нибудь про stable - dev если есть.

2019-09-09 13:11 UTC, DudaGod commented on README.md
> +Describe browser in hermione [config](https://github.com/gemini-testing/hermione#browsers) for running tests on healess mode.
а для чего тут эта строка?
Я бы тут сначала ожидал увидеть информацию о настройке плагина

2019-09-09 13:11 UTC, DudaGod commented on README.md
> +For example you can override accessKey option like so:
копипаста с прошлого плагина. У тебя тут `accessKey` нет

2019-09-09 13:11 UTC, DudaGod commented on lib/chrome.js
> +'use strict';
я бы переименовал этот класс в `chrome-downloader`. Сейчас его название не соответствет тому, что в нем происходит

2019-09-09 13:11 UTC, DudaGod commented on index.js
> +    const chrome = Chrome.create(config, browser);
для чего нам тут создавать инстанс этого класса во всех воркерах и мастере?

2019-09-09 13:11 UTC, DudaGod commented on lib/chrome.js
> +'use strict';
И он слишком много на себя берет. Все, что он должен сделать это скачать версию хромиума, а за перенастройку конфига браузера в hermione он не должен отвечать и вообще ничего знать про него не должен

2019-09-09 13:11 UTC, DudaGod commented on lib/chrome.js
> +    static create(config, browser) {
Мы его обычно используем для удобного тестирования, что инстанс был создан

2019-09-09 13:11 UTC, DudaGod commented on index.js
> +            await chrome.setUp();
по этому `setUp` вообще не понятно, что происходит внутри.
Почему не переименовать его в `download`? Он будет возвращать путь до бинаря и в другой функции мы просто заюзаем его

2019-09-09 13:11 UTC, DudaGod commented on lib/chrome.js
> +        await utils.makeChromiumDir(cachePath);
почему просто не передать `this._config.cachePath`? Ты же ниже нигде переменную `cachePath` не юзаешь

2019-09-09 13:11 UTC, DudaGod commented on lib/utils.js
> +        return await fs.ensureDir(cachePath);
зачем тут `await`? Ты же при вызове этой функции тоже пишешь `await`. В итоге у тебя получается `await await`

2019-09-09 13:11 UTC, DudaGod commented on lib/utils.js
> +        throw new Error(`Could not create directory for downloaded Chromium: ${e}`);
почему `downloaded`? Ты тут еще ничего не скачал же. Правильнее написать для `headless chromium`

2019-09-09 13:11 UTC, DudaGod commented on lib/chrome.js
> +        chromeOptions.args = _.union(args, ['headless']);
Зачем тут `union`? Если тебе просто нужно добавить в массив строку `headless` если его еще нет в `args`?

2019-09-09 13:11 UTC, DudaGod commented on lib/chrome.js
> +        chromeOptions.binary = chromiumPath;
```
desiredCapabilities.chromeOptions = _.merge(desiredCapabilities.chromeOptions || {}, {
  args: ['headless'],
  binary: chromiumPath
});
```

Либо нужно `mergeWith` юзнуть, чтобы в случае массива не дублировать `headless` по два раза

2019-09-09 13:11 UTC, DudaGod commented on lib/chrome.js
> +const {CHROMIUM_RETRIES_COUNT} = require('./constants/defaults');
было бы круто если бы это было опцией плагина иначе пользователь никак не может влиять на эту захардкоженную константу

2019-09-09 13:11 UTC, DudaGod commented on lib/chrome.js
> +        this._installPath = null;
это для чего?

2019-09-09 13:11 UTC, DudaGod commented on lib/utils.js
> +        } else {
зачем тут `else`?

2019-09-09 13:11 UTC, DudaGod commented on lib/utils.js
> +    }
я бы так писал:
```js
if (platform === 'darwin') {
  return 'mac';
}

if (paltform === 'win32') {
  return arch === 'x64' ? 'win64' : 'win';
}

return platform;
```

2019-09-09 13:11 UTC, DudaGod commented on lib/utils.js
> +    let passedVersion = version;
для чего здесь переменная `passedVersion`

2019-09-09 13:11 UTC, DudaGod commented on lib/chrome.js
> +        if (!_.isUndefined(revisionFromFile)) {
не понял зачем тут проверка на `!_isUndefined`? Почему просто нельзя `if(...)` юзнуть?

2019-09-09 13:11 UTC, DudaGod commented on lib/utils.js
> +    if (osName === 'win64') {
давай хотя бы комментарий к коду напишем

2019-09-09 13:11 UTC, DudaGod commented on lib/constants/revisions.json
> +}
отступ пропал

2019-09-09 13:11 UTC, DudaGod commented on lib/utils.js
> +    if (_.isEmpty(version)) {
зачем тут `isEmpty` не понимаю? У тебя же есть просто восклицательный знак - юзай его

2019-09-09 13:11 UTC, DudaGod commented on lib/utils.js
> +const getStableVersionsForOs = async (osName) => {
почему бы так не назвать - `getStableOsVersions`? Без `for`?

2019-09-09 13:11 UTC, DudaGod commented on lib/utils.js
> +        throw new Error(`"hermione-headless-chrome" could not get Chromium full versions: ${e}`);
почему у тебя в некоторых командах добавляется в ошибку название плагина? А в некоторых нет? Видно же будет по стектрейсу, что ошибка прилетела именно из этого плагина

2019-09-09 13:11 UTC, DudaGod commented on lib/chrome.js
> +        const revision = await utils.requestRevision(fullVersion);
для чего тут три вызова делать? Почему просто не позвать `await utils.getLastRevision`?

2019-09-09 13:11 UTC, DudaGod commented on lib/utils.js
> +        throw new Error(`Passed Chromium version "${shortVer}" was not found`);
`shortVer` же может быть не указан

2019-09-09 13:11 UTC, DudaGod commented on lib/utils.js
> +        shortVer += '.';
Зачем этим заниматься? Почему просто не писать мажорные версии и ставить последнюю мажорную? Ну вот реально я не могу представить кейс когда кому-то нужно поставить версию `69.15.25...`

2019-09-09 13:11 UTC, DudaGod commented on lib/chrome.js
> +        // decrement the commit number for finding build: https://www.chromium.org/getting-involved/download-chromium
это разве не `revision number`?

2019-09-09 13:11 UTC, DudaGod commented on lib/chrome.js
> +const {CHROMIUM_RETRIES_COUNT} = require('./constants/defaults');
И название так себе. Сходу по нему не понятно, что же должно заретраится

2019-09-09 13:11 UTC, DudaGod commented on lib/chrome.js
> +                if (e.message === 'Response code 404 (Not Found)') {
почему бы просто на `404` не сматчится? Там код ошибки отдельным полем не летит?

2019-09-09 13:11 UTC, DudaGod commented on lib/chrome.js
> +            throw new Error('"hermione-headless-chrome" could not found Chromium build. Check your internet connection or choose another version');
опять название плагина в ошибке. И я бы писал количество попыток за которое не получилось скачать chromium

2019-09-09 13:11 UTC, DudaGod commented on lib/constants/defaults.js
> +        cachePath: os.homedir(),
давай писать в темповую директорию и нужно еще путь до chromium бинаря писать, т.е. куда он сохранился в итоге

2019-09-09 13:11 UTC, DudaGod commented on scripts/updateRevisions.js
> +    updateRevisions();
где await?

2019-09-09 13:11 UTC, DudaGod commented on scripts/updateRevisions.js
> +            for (let i = 0; i < CHROMIUM_RETRIES_COUNT; i++) {
этот код у тебя дублируется кстати. Имело бы смысл его куда-то вынести

2019-09-09 13:11 UTC, DudaGod commented on scripts/updateRevisions.js
> +        for (let ver = lastInFile; ver <= lastStable; ver++) {
зачем для старых версий делать опять обновления? Бери последнюю текущую версию в файле и со следующей обновляй

2019-09-09 13:54 UTC, CatWithApple commented on lib/constants/defaults.js
> +    REVISIONS_PATH: path.join(process.cwd(), 'lib/constants/revisions.json'),
если revisions.json - это часть исходников, то нельзя использовать process.cwd() как часть пути.

2019-09-09 13:56 UTC, CatWithApple commented on lib/utils.js
> +    const chromiumDirPath = path.join(basePath, PLUGIN_NAME);
если не указать путь для хромиумов в конфиге, то путь должен быть home/PLUGIN_NAME, а если указать, то не нужно добавлять PLUGIN_NAME

2019-09-09 14:03 UTC, CatWithApple commented on lib/utils.js
> +        return await fs.ensureDir(cachePath);
тут await по делу. без него try/catch не поймает ошибку.

2019-09-09 14:07 UTC, CatWithApple commented on lib/utils.js
> +        throw new Error(`"hermione-headless-chrome" could not get Chromium full versions: ${e}`);
> Видно же будет по стектрейсу, что ошибка прилетела именно из этого плагина

не факт

2019-09-09 14:09 UTC, CatWithApple commented on lib/utils.js
> +        shortVer += '.';
Если хочешь сделать тесты стабильными, то есть смысл указывать версию с точностью до билда.

2019-09-09 14:13 UTC, CatWithApple commented on scripts/updateRevisions.js
> +    updateRevisions();
тут await нельзя использовать, т.к. код не в async функции.
и такой try/catch не сработает, конечно.
async функция возвращает промис (по определению). посмотри как обработать ошибку промиса:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

2019-09-09 19:48 UTC, DudaGod commented on scripts/updateRevisions.js
> +    updateRevisions();
уточню, что я своим вопросом подразумевал, что нужно `async` функцию заюзать

2019-09-09 19:52 UTC, DudaGod commented on lib/utils.js
> +        shortVer += '.';
так если ты старую версию указываешь допустим - `66`, то тебе всегда будет приезжаеть одна и таже - `66.N.N.N`. Вот тебе и стабильность. Единственное не будет работать с последней версией, так как могут апдейты приезжать. В общем в этом месте нужно подумать.

2019-09-11 10:44 UTC, TheNech commented on lib/chrome.js
> +                if (e.message === 'Response code 404 (Not Found)') {
Может возникнуть не только сетевая ошибка

2019-09-11 10:55 UTC, TheNech commented on README.md
> +NB: plugin searches builds starting from last stable version, but downloaded developers version. Builds for some versions may not be found.
На сайте с архивами нет архивов для ревизий стабильных версий, поэтому только dev.

2019-09-16 10:05 UTC, sipayRT reviewed
Я не увидел тестов на то, что при добавлении опций в капабилити мы не перетираем существующие (это важно)

2019-09-16 10:05 UTC, sipayRT commented on README.md
> +* **cachePath** (optional) `String` - path to directory for downloaded Chromium binary; */hermione-headless-hrome* on *home directory* by default.
hermione-headless-**C**hrome

2019-09-16 10:05 UTC, sipayRT commented on README.md
> +* **downloadAttempts** (optional) `Number` - attempts count for download Chromium; `50` by default
зачем столько попыток то?

2019-09-16 10:05 UTC, sipayRT commented on README.md
> +$ hermione_headless_chrome_browser_id=some-browser-id hermione test
у тебя слово `test` выглядит как команда

2019-09-16 10:05 UTC, sipayRT commented on lib/constants/revisions.json
> +        "60": "474896",
зачем нам столько версий? можно поддерживать 3 последних и всё

2019-09-16 10:05 UTC, sipayRT commented on lib/downloadChromium.js
> +            console.log(`Chromium binary was downloaded to '${chromiumPath}'\n`);
console.info

2019-09-16 10:05 UTC, sipayRT commented on lib/downloadChromium.js
> +            if (e.message === 'Response code 404 (Not Found)') {
почему здесь нельзя матчиться на сам код ошибки? матчиться на такую строку - не самый надежный способ. Как минимум, тут лучше регулярку использовать

2019-09-16 10:05 UTC, sipayRT commented on lib/downloadChromium.js
> +        throw new Error(`Could not found Chromium build in ${downloadAttempts} retries. Increase retries count or choose another version`);
found -> find?

2019-09-16 10:05 UTC, sipayRT commented on lib/utils.js
> +        throw new Error('Could not create directory headless Chromium:', e);
...directory **for** Chromium

2019-09-16 10:05 UTC, sipayRT commented on lib/utils.js
> +const makeChromiumDir = async (cachePath) => {
я бы вообще в названии не завязывался на слово Chromium - это абстрактных хелпер, который создает директорию

2019-09-16 10:05 UTC, sipayRT commented on lib/utils.js
> +        return arch === 'x64' ? 'win64' : 'win';
чет я не понял. для обоих архитектур платформа называется 'win32'?

2019-09-16 10:05 UTC, sipayRT commented on lib/utils.js
> +    const url = `https://omahaproxy.appspot.com/deps.json?version=${fullVersion}`;
прям напрашивается или константа хоста, или вообще его конфигурация

2019-09-16 10:05 UTC, sipayRT commented on lib/utils.js
> +        throw new Error('Could not get Chromium revsion number:', e);
rev**i**sion

2019-09-16 10:05 UTC, sipayRT commented on lib/utils.js
> +        shortVer += '.';
а зачем вообще эту точку доклеивать? типа, если чистый мажор, то ее там не будет? вообще не понимаю важности этой точки при поиске

2019-09-16 10:05 UTC, sipayRT commented on scripts/updateRevisions.js
> +    console.log('Start update revisions\n');
console.info

2019-09-16 10:05 UTC, sipayRT commented on scripts/updateRevisions.js
> +                    revisionsForOs[ver] = String(revision);
зачем явно к строке приводить?

2019-09-16 10:05 UTC, sipayRT commented on scripts/updateRevisions.js
> +                        throw new Error(`Could not download Chromium: ${e}`);
добавь в ошибку номер ревизии

2019-09-16 10:05 UTC, sipayRT commented on test/unit/index.js
> +        assert.deepEqual(expectedBrowser, browser);
в проверку сначала должен передаваться actual, а потом уже expected

2019-09-16 10:05 UTC, sipayRT commented on test/unit/index.js
> +    afterEach(() => sinon.restore());
у sinon-а вроде нет такого метода (или он ничего не делает). Это у sandbox-а можно восстанавливать его состояние

2019-09-16 10:05 UTC, sipayRT commented on test/unit/lib/utils.js
> +            sinon.stub(process, 'platform').value('linux');
значения для стаба лучше брать какие-нибудь абстрактные

2019-09-16 10:05 UTC, sipayRT commented on test/unit/lib/utils.js
> +            assert.equal(revision, 6525);
стаб со значением 6525 лучше здесь рядом указать, чтобы не вспоминать откуда вообще это значение взялось

2019-09-16 10:26 UTC, TheNech commented on lib/utils.js
> +        return arch === 'x64' ? 'win64' : 'win';
Да, только 'win32'
https://nodejs.org/api/os.html#os_os_platform

2019-09-16 17:18 UTC, CatWithApple commented on .gitignore
> +.DS_Store
lib/.DS_Store удалить нужно и правильно настроить gitignore

2019-09-16 17:18 UTC, CatWithApple commented on lib/utils.js
> +        throw new Error(`Could not get Chromium last stable version for ${osName}:`, e);
не правильно используешь конструктор Error. второй аргумент - fileName(и то это не стандарт даже и в node второго аргумента нет).
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error 
https://nodejs.org/dist/latest-v12.x/docs/api/errors.html#errors_new_error_message
в других местах тоже стоит поправить

2019-09-16 17:18 UTC, CatWithApple commented on lib/utils.js
> +        throw new Error(`Could not get Chromium last stable version for ${osName}:`, e);
возможно, есть смысл прикрутить https://www.npmjs.com/package/nested-error-stacks

2019-09-16 17:18 UTC, CatWithApple commented on lib/utils.js
> +        throw new Error('Unsupported platform for downloading Chromium');
Тут хорошо бы вывести какая именно платформа не поддерживается. Больше данных в тексте ошибки - проще потом понять проблему.

2019-09-16 17:18 UTC, CatWithApple commented on scripts/updateRevisions.js
> +    console.log('Start update revisions\n');
зачем доп перевод строки в console.log тут и выше?

2019-09-16 17:18 UTC, CatWithApple commented on scripts/updateRevisions.js
> +(async () => {
можно проще.
```
updateRevisions().catch(e => {
   console.error('\nCould not update Chromium revisions file:', e);
})
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch

2019-09-16 17:18 UTC, CatWithApple commented on scripts/updateRevisions.js
> +'use sctrict';
И я бы ещё в каждый запускаемый скрипт добавлял
```
process.on('unhandledRejection', (reason, p) => {
    console.error('Unhandled Rejection:\nPromise: ', p, '\nReason: ', reason);
});
```

https://nodejs.org/api/process.html#process_event_unhandledrejection

2019-09-16 17:18 UTC, CatWithApple commented on scripts/updateRevisions.js
> +        for (let ver = +lastInFile + 1; ver <= lastStable; ver++) {
я бы сделал явное приведение типа для lastInFile.
и `+ 1` смотрится так себе. хорошо бы такие штуки выделять в переменную с названием, которое будет заменять комментарий.

2019-09-16 17:18 UTC, CatWithApple commented on test/unit/index.js
> +    let parseConfig = sinon.stub();
let -> const

2019-09-16 17:18 UTC, CatWithApple commented on test/unit/index.js
> +        downloadChromium = sinon.stub();
в чем разница между downloadChromium и parseConfig для тестов? почему они инициализируются в разных местах?

2019-09-16 17:18 UTC, CatWithApple commented on test/unit/index.js
> +    const initPlugin = (hermione, opts = {enabled: true}) => {
тут не нужен дефолт для opts

2019-09-16 17:18 UTC, CatWithApple commented on lib/downloadChromium.js
> +const downloadChromium = require('download-chromium');
тут получилась непонятка. 
файл downloadChromium.js. а внутри рекваерим 'download-chromium'. и не понятно зачем наш код вообще нужен.

2019-09-16 17:18 UTC, CatWithApple commented on lib/downloadChromium.js
> +'use strict';
поправь, пожалуйста, имена файлов в `kebab-case`.
я не могу найти где-то соглашение про это, но в gemini-testing так принято.
нашел такую аргументацию (вроде валидно):
https://stackoverflow.com/a/44882336

2019-09-16 17:18 UTC, CatWithApple commented on lib/utils.js
> +const makeChromiumDir = async (cachePath) => {
вообще не понятно зачем такой хелпер. пусть бы ловились исключения на самом верхнем уровне плагина. 
мы тут не сильно можем добавить контекста и подробностей.

2019-09-17 06:30 UTC, TheNech commented on scripts/updateRevisions.js
> +    console.log('Start update revisions\n');
> зачем доп перевод строки в console.log тут и выше?

Так лог красивее

2019-09-17 06:32 UTC, TheNech commented on .gitignore
> +.DS_Store
> правильно настроить gitignore

Что именно нужно добавить в gitignore?

2019-09-17 07:15 UTC, TheNech commented on test/unit/index.js
> +        downloadChromium = sinon.stub();
Проверил: не было причины инициализировать их в разных местах. Исправил

2019-09-17 07:39 UTC, TheNech commented
/fixed @sipayRT @CatWithApple

2019-09-17 11:53 UTC, CatWithApple approved these changes

2019-09-17 11:53 UTC, CatWithApple commented on .gitignore
> +.DS_Store
посмотри документацию, пожалуйста:
https://git-scm.com/docs/gitignore#_pattern_format

2019-09-17 11:53 UTC, CatWithApple commented on README.md
> +* **enabled** (optional) `Boolean` – enable/disable the plugin; by default plugin is enabled
в конце нет точки, а в других пунктах есть

2019-09-17 11:53 UTC, CatWithApple commented on index.js
> +const parseConfig = require('./lib/config');
тут и ниже. 
если файл экспортирует одну сущность, хорошо чтобы имя файла соответствовало имени переменной, в которую рекваерим. так код намного проще понимать.

2019-09-17 11:53 UTC, CatWithApple commented on lib/utils.js
> +const makeDir = async (cachePath) => {
теперь это точно бесполезная обертка, которая не делает ничего полезного

2019-09-17 11:53 UTC, CatWithApple commented on lib/download-chromium-by-version.js
> +            if (e.message.match(/Response code 404/)) { // e.originalError.statusCode
о чем комментарий?

2019-09-17 11:53 UTC, CatWithApple commented on lib/utils.js
> +        console.error(e);
так делать можно, но мне больше нравятся вложенные ошибки. 
на твоё усмотрение.

2019-09-17 11:53 UTC, CatWithApple commented on lib/utils.js
> +        const filePath = path.resolve(__dirname, './constants/revisions.json');
на всякий случай напишу, что этот файл можно было просто зарекваерить.

2019-09-17 11:53 UTC, CatWithApple commented on lib/utils.js
> +    const versions = _.map(response.body, (obj) => obj.version).sort(compareVersions).reverse();
в переменной versions  нет необходимости

2019-09-17 11:53 UTC, CatWithApple commented on lib/utils.js
> +    const fullVersion = _.find(versions, (item) => _.startsWith(item, shortVer));
`смотрю подозрительно на startsWith`

2019-09-17 11:53 UTC, CatWithApple commented on scripts/update-revisions.js
> +                    revisionsForOs[ver] = +revision;
тут тоже лучше заменить на явное приведение типов

2019-09-17 11:53 UTC, CatWithApple commented on scripts/update-revisions.js
> +                        throw new Error(`Could not find Chromium revision ${revision}`);
`Could not find Chromium revision for version ${ver}` ?

2019-09-17 11:53 UTC, CatWithApple commented on scripts/update-revisions.js
> +        const file = await fs.readFile(REVISIONS_PATH);
readFile -> readJSON

2019-09-17 12:34 UTC, CatWithApple commented on scripts/update-revisions.js
> +    console.error('\nCould not update Chromium revisions file:', e);
ещё стоит добавить не нулевой код выхода.
```
process.exit(1);
```
https://nodejs.org/api/process.html#process_process_exit_code
https://en.wikipedia.org/wiki/Exit_status

2019-09-17 12:44 UTC, TheNech commented on lib/download-chromium-by-version.js
> +            if (e.message.match(/Response code 404/)) { // e.originalError.statusCode
Это лишний комментарий про сетевую ошибку

2019-09-17 12:45 UTC, TheNech commented on lib/utils.js
> +        const filePath = path.resolve(__dirname, './constants/revisions.json');
Он раньше рекваерился, но тогда его сложнее стабать

2019-09-17 12:47 UTC, CatWithApple commented on lib/utils.js
> +        const filePath = path.resolve(__dirname, './constants/revisions.json');
proxyrequire?

2019-09-17 13:11 UTC, TheNech commented on .gitignore
> +.DS_Store
Это имеешь в виду `**/.DS_Store` ?

2019-09-30 10:08 UTC, merged